FILENAME R0112345 "data.xml";
FILENAME map "map.xml";
LIBNAME R0112345 xml xmlmap=map access=readonly;
PROC DATASETS LIBRARY=R0112345;
COPY OUT=work; RUN; PROC FORMAT;

VALUE $CL_7_
	"1"="Normal"
	"4"="Anormal"
	"999"="No examinado";
VALUE CL_8_
	1="Normal"
	4="Anormal";
VALUE CL_3_
	1="Normal"
	2="Abnormal"
	99="Not Examined";
VALUE CL_4_
	1="Normal"
	2="Abnormal";
VALUE CL_10_
	1="Yes"
	0="No"
	-99="N/A";
VALUE CL_12_
	1="Yes"
	0="No"
	-88="Unknown";
VALUE CL_14_
	1="Yes"
	0="No";
VALUE CL_17_
	1="YES"
	0="NO";
VALUE CL_25_
	1="Yes"
	0="No";
VALUE CL_27_
	1="Mild"
	2="Moderate"
	3="Severe";
VALUE CL_28_
	0="Not Related"
	1="Unlikely Related"
	2="Possibly Related"
	3="Related";
VALUE CL_29_
	0="Dose Increased"
	1="Dose Not Changed"
	2="Dose Reduced"
	3="Drug Interrupted"
	4="Drug Withdrawn"
	5="Not Applicable"
	6="Unknown";
VALUE CL_30_
	1="Recovered"
	2="Still under treatment/observation"
	3="Alive with sequelae"
	4="Died";
VALUE CL_19_
	1="Yes"
	0="No";
VALUE CL_21_
	1="Mild"
	2="Moderate"
	3="Severe";
VALUE CL_22_
	0="Not Related"
	1="Unlikely Related"
	2="Possibly Related"
	3="Related";
VALUE CL_23_
	0="Dose Increased"
	1="Dose Not Changed"
	2="Dose Reduced"
	3="Drug Interrupted"
	4="Drug Withdrawn"
	5="Not Applicable"
	6="Unknown";
VALUE CL_24_
	1="Recovered"
	2="Still under treatment/observation"
	3="Alive with sequelae"
	4="Died";
VALUE CL_32_
	1="yes"
	0="no";
RUN;


DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT APPEARAN CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT SKIN CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT HEENT CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT THYROID CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT CHEST CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT LUNGS CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT BREAST CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT HEART CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT ABDOMEN CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT MUSCULOS CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT GENITALI CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT PELVIS CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT RECTAL CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT PROSTATE CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT VASCULAR CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT NEUROLOG CL_7_; RUN;

DATA IG_PHYSI_UNGROUPED;
SET IG_PHYSI_UNGROUPED;
FORMAT LYMPHNOD CL_7_; RUN;

DATA IG_PHYSI_OTHERBODYSYSTEMSITE;
SET IG_PHYSI_OTHERBODYSYSTEMSITE;
FORMAT OTHER00c CL_8_; RUN;

DATA IG_AGENT_UNGROUPED;
SET IG_AGENT_UNGROUPED;
FORMAT MTD_DETE CL_10_; RUN;

DATA IG_AGENT_UNGROUPED;
SET IG_AGENT_UNGROUPED;
FORMAT AGEN_INT CL_10_; RUN;

DATA IG_AGENT_UNGROUPED;
SET IG_AGENT_UNGROUPED;
FORMAT RESTARTE CL_10_; RUN;

DATA IG_AGENT_UNGROUPED;
SET IG_AGENT_UNGROUPED;
FORMAT REG_MOD CL_10_; RUN;

DATA IG_AGENT_UNGROUPED;
SET IG_AGENT_UNGROUPED;
FORMAT COMPLIAN CL_12_; RUN;

DATA IG_AGENT_UNGROUPED;
SET IG_AGENT_UNGROUPED;
FORMAT AGEN_PRO CL_10_; RUN;

DATA IG_VERIF_UNGROUPED;
SET IG_VERIF_UNGROUPED;
FORMAT ELIGIBIL CL_14_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT OVER_18 CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT ECOG_STA CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT WBC_CT CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT PLATELET CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT SERUM_CR CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT SERUM_BI CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT CONTRACE CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT INFORMED CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT HIST_HEA CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT CHEMOTHE CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT FASTING_ CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT NSAIDS CL_17_; RUN;

DATA IG_ELIGI_UNGROUPED;
SET IG_ELIGI_UNGROUPED;
FORMAT OTH_INVE CL_17_; RUN;

DATA IG_ADVER_UNGROUPED;
SET IG_ADVER_UNGROUPED;
FORMAT _1_AEYN CL_25_; RUN;

DATA IG_ADVER_UNGROUPED;
SET IG_ADVER_UNGROUPED;
FORMAT _1_AESEV CL_27_; RUN;

DATA IG_ADVER_UNGROUPED;
SET IG_ADVER_UNGROUPED;
FORMAT _1_AESER CL_25_; RUN;

DATA IG_ADVER_UNGROUPED;
SET IG_ADVER_UNGROUPED;
FORMAT _1_AEREL CL_28_; RUN;

DATA IG_ADVER_UNGROUPED;
SET IG_ADVER_UNGROUPED;
FORMAT _1_AEACN CL_29_; RUN;

DATA IG_ADVER_UNGROUPED;
SET IG_ADVER_UNGROUPED;
FORMAT _1_AEOUT CL_30_; RUN;

DATA IG_ADVER_UNGROUPED;
SET IG_ADVER_UNGROUPED;
FORMAT _2_AEYN CL_25_; RUN;

DATA IG_ADVER_AE2;
SET IG_ADVER_AE2;
FORMAT _2_AESEV CL_27_; RUN;

DATA IG_ADVER_AE2;
SET IG_ADVER_AE2;
FORMAT _2_AESER CL_25_; RUN;

DATA IG_ADVER_AE2;
SET IG_ADVER_AE2;
FORMAT _2_AEREL CL_28_; RUN;

DATA IG_ADVER_AE2;
SET IG_ADVER_AE2;
FORMAT _2_AEACN CL_29_; RUN;

DATA IG_ADVER_AE2;
SET IG_ADVER_AE2;
FORMAT _2_AEOUT CL_30_; RUN;

DATA IG_ADVER_AE2;
SET IG_ADVER_AE2;
FORMAT _3_AEYN CL_25_; RUN;

DATA IG_ADVER_AE2;
SET IG_ADVER_AE2;
FORMAT _2_AEYN CL_25_; RUN;

DATA IG_ADVER_AE3;
SET IG_ADVER_AE3;
FORMAT _3_AESEV CL_27_; RUN;

DATA IG_ADVER_AE3;
SET IG_ADVER_AE3;
FORMAT _3_AESER CL_25_; RUN;

DATA IG_ADVER_AE3;
SET IG_ADVER_AE3;
FORMAT _3_AEREL CL_28_; RUN;

DATA IG_ADVER_AE3;
SET IG_ADVER_AE3;
FORMAT _3_AEACN CL_29_; RUN;

DATA IG_ADVER_AE3;
SET IG_ADVER_AE3;
FORMAT _3_AEOUT CL_30_; RUN;

DATA IG_ADVER_AE3;
SET IG_ADVER_AE3;
FORMAT _4_AEYN CL_25_; RUN;

DATA IG_ADVER_AE3;
SET IG_ADVER_AE3;
FORMAT _3_AEYN CL_25_; RUN;

DATA IG_ADVER_AE4;
SET IG_ADVER_AE4;
FORMAT _4_AESEV CL_27_; RUN;

DATA IG_ADVER_AE4;
SET IG_ADVER_AE4;
FORMAT _4_AESER CL_25_; RUN;

DATA IG_ADVER_AE4;
SET IG_ADVER_AE4;
FORMAT _4_AEREL CL_28_; RUN;

DATA IG_ADVER_AE4;
SET IG_ADVER_AE4;
FORMAT _4_AEACN CL_29_; RUN;

DATA IG_ADVER_AE4;
SET IG_ADVER_AE4;
FORMAT _4_AEOUT CL_30_; RUN;

DATA IG_ADVER_AE4;
SET IG_ADVER_AE4;
FORMAT _4_AEYN CL_25_; RUN;

DATA IG_ADVER_AE5;
SET IG_ADVER_AE5;
FORMAT _5_AEYN CL_25_; RUN;

DATA IG_ADVER_AE5;
SET IG_ADVER_AE5;
FORMAT _5_AESEV CL_27_; RUN;

DATA IG_ADVER_AE5;
SET IG_ADVER_AE5;
FORMAT _5_AESER CL_25_; RUN;

DATA IG_ADVER_AE5;
SET IG_ADVER_AE5;
FORMAT _5_AEREL CL_28_; RUN;

DATA IG_ADVER_AE5;
SET IG_ADVER_AE5;
FORMAT _5_AEACN CL_29_; RUN;

DATA IG_ADVER_AE5;
SET IG_ADVER_AE5;
FORMAT _5_AEOUT CL_30_; RUN;

DATA IG_CONCO_CONCOMITANTMEDICATIONS;
SET IG_CONCO_CONCOMITANTMEDICATIONS;
FORMAT Con_M00i CL_32_; RUN;