CREATE FOREIGN TABLE public.ft_archived_dataset_file (archived_dataset_file_id integer, name character varying(255), dataset_id integer, export_format_id integer, file_reference character varying(1000), run_time integer, file_size integer, date_created timestamp(6) without time zone, owner_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'archived_dataset_file', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_audit_event (audit_id integer, audit_date timestamp with time zone, audit_table character varying(500), user_id integer, entity_id integer, reason_for_change character varying(1000), action_message character varying(4000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'audit_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_audit_event_context (audit_id integer, study_id integer, subject_id integer, study_subject_id integer, role_name character varying(200), event_crf_id integer, study_event_id integer, study_event_definition_id integer, crf_id integer, crf_version_id integer, study_crf_id integer, item_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'audit_event_context', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_audit_event_values (audit_id integer, column_name character varying(255), old_value character varying(2000), new_value character varying(2000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'audit_event_values', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_audit_log_event (audit_id integer, audit_date timestamp with time zone, audit_table character varying(500), user_id integer, entity_id integer, entity_name character varying(500), reason_for_change character varying(1000), audit_log_event_type_id integer, old_value character varying(4000), new_value character varying(4000), event_crf_id integer, study_event_id integer, event_crf_version_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'audit_log_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_audit_log_event_type (audit_log_event_type_id integer, name character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'audit_log_event_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_audit_user_login (id integer, user_name character varying(255), user_account_id integer, login_attempt_date timestamp with time zone, login_status_code integer, version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'audit_user_login', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_authorities (id integer, username character varying(50), authority character varying(50), version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'authorities', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_completion_status (completion_status_id integer, status_id integer, name character varying(255), description character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'completion_status', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_configuration (id integer, key character varying(255), value character varying(255), description character varying(512), version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'configuration', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_crf (crf_id integer, status_id integer, name character varying(255), description character varying(2048), owner_id integer, date_created date, date_updated date, update_id integer, oc_oid character varying(40), source_study_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'crf', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_crf_version (crf_version_id integer, crf_id integer, name character varying(255), description character varying(4000), revision_notes character varying(255), status_id integer, date_created date, date_updated date, owner_id integer, update_id integer, oc_oid character varying(40))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'crf_version', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_databasechangelog (id character varying(63), author character varying(63), filename character varying(200), dateexecuted timestamp with time zone, md5sum character varying(32), description character varying(255), comments character varying(255), tag character varying(255), liquibase character varying(10))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'databasechangelog', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_databasechangeloglock (id integer, locked boolean, lockgranted timestamp with time zone, lockedby character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'databasechangeloglock', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dataset (dataset_id integer, study_id integer, status_id integer, name character varying(255), description character varying(2000), sql_statement text, num_runs integer, date_start date, date_end date, date_created date, date_updated date, date_last_run date, owner_id integer, approver_id integer, update_id integer, show_event_location boolean, show_event_start boolean, show_event_end boolean, show_subject_dob boolean, show_subject_gender boolean, show_event_status boolean, show_subject_status boolean, show_subject_unique_id boolean, show_subject_age_at_event boolean, show_crf_status boolean, show_crf_version boolean, show_crf_int_name boolean, show_crf_int_date boolean, show_group_info boolean, show_disc_info boolean, odm_metadataversion_name character varying(255), odm_metadataversion_oid character varying(255), odm_prior_study_oid character varying(255), odm_prior_metadataversion_oid character varying(255), show_secondary_id boolean, dataset_item_status_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dataset', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dataset_crf_version_map (dataset_id integer, event_definition_crf_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dataset_crf_version_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dataset_filter_map (dataset_id integer, filter_id integer, ordinal integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dataset_filter_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dataset_item_status (dataset_item_status_id integer, name character varying(50), description character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dataset_item_status', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dataset_study_group_class_map (dataset_id integer, study_group_class_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dataset_study_group_class_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dc_computed_event (dc_summary_event_id integer, dc_event_id integer, item_target_id integer, summary_type character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dc_computed_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dc_event (dc_event_id integer, decision_condition_id integer, ordinal integer, type character varying(256))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dc_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dc_primitive (dc_primitive_id integer, decision_condition_id integer, item_id integer, dynamic_value_item_id integer, comparison character varying(3), constant_value character varying(4000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dc_primitive', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dc_section_event (dc_event_id integer, section_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dc_section_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dc_send_email_event (dc_event_id integer, to_address character varying(1000), subject character varying(1000), body character varying(4000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dc_send_email_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dc_substitution_event (dc_event_id integer, item_id integer, value character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dc_substitution_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dc_summary_item_map (dc_summary_event_id integer, item_id integer, ordinal integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dc_summary_item_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_decision_condition (decision_condition_id integer, crf_version_id integer, status_id integer, label character varying(1000), comments character varying(3000), quantity integer, type character varying(3), owner_id integer, date_created date, date_updated date, update_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'decision_condition', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_discrepancy_note (discrepancy_note_id integer, description character varying(255), discrepancy_note_type_id integer, resolution_status_id integer, detailed_notes character varying(1000), date_created date, owner_id integer, parent_dn_id integer, entity_type character varying(30), study_id integer, assigned_user_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'discrepancy_note', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_discrepancy_note_type (discrepancy_note_type_id integer, name character varying(50), description character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'discrepancy_note_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dn_age_days (discrepancy_note_id integer, days integer, age integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dn_age_days', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dn_event_crf_map (event_crf_id integer, discrepancy_note_id integer, column_name character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dn_event_crf_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dn_item_data_map (item_data_id integer, discrepancy_note_id integer, column_name character varying(255), study_subject_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dn_item_data_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dn_study_event_map (study_event_id integer, discrepancy_note_id integer, column_name character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dn_study_event_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dn_study_subject_map (study_subject_id integer, discrepancy_note_id integer, column_name character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dn_study_subject_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dn_subject_map (subject_id integer, discrepancy_note_id integer, column_name character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dn_subject_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dyn_item_form_metadata (id integer, item_form_metadata_id integer, item_id integer, crf_version_id integer, show_item boolean, event_crf_id integer, version integer, item_data_id integer, passed_dde integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dyn_item_form_metadata', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_dyn_item_group_metadata (id integer, item_group_metadata_id integer, item_group_id integer, show_group boolean, event_crf_id integer, version integer, passed_dde integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'dyn_item_group_metadata', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_event_crf (event_crf_id integer, study_event_id integer, crf_version_id integer, date_interviewed date, interviewer_name character varying(255), completion_status_id integer, status_id integer, annotations character varying(4000), date_completed timestamp with time zone, validator_id integer, date_validate date, date_validate_completed timestamp with time zone, validator_annotations character varying(4000), validate_string character varying(256), owner_id integer, date_created date, study_subject_id integer, date_updated date, update_id integer, electronic_signature_status boolean, sdv_status boolean, old_status_id integer, sdv_update_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'event_crf', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_event_definition_crf (event_definition_crf_id integer, study_event_definition_id integer, study_id integer, crf_id integer, required_crf boolean, double_entry boolean, require_all_text_filled boolean, decision_conditions boolean, null_values character varying(255), default_version_id integer, status_id integer, owner_id integer, date_created date, date_updated date, update_id integer, ordinal integer, electronic_signature boolean, hide_crf boolean, source_data_verification_code integer, selected_version_ids character varying(150), parent_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'event_definition_crf', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_export_format (export_format_id integer, name character varying(255), description character varying(1000), mime_type character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'export_format', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_filter (filter_id integer, name character varying(255), description character varying(2000), sql_statement character varying(4000), status_id integer, date_created date, date_updated date, owner_id integer, update_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'filter', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_filter_crf_version_map (filter_id integer, crf_version_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'filter_crf_version_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_group_class_types (group_class_type_id integer, name character varying(255), description character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'group_class_types', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_item (item_id integer, name character varying(255), description character varying(4000), units character varying(64), phi_status boolean, item_data_type_id integer, item_reference_type_id integer, status_id integer, owner_id integer, date_created date, date_updated date, update_id integer, oc_oid character varying(40))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'item', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_item_data (item_data_id integer, item_id integer, event_crf_id integer, status_id integer, value character varying(4000), date_created date, date_updated date, owner_id integer, update_id integer, ordinal integer, old_status_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'item_data', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_item_data_type (item_data_type_id integer, code character varying(20), name character varying(255), definition character varying(1000), reference character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'item_data_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_item_form_metadata (item_form_metadata_id integer, item_id integer, crf_version_id integer, header character varying(2000), subheader character varying(240), parent_id integer, parent_label character varying(120), column_number integer, page_number_label character varying(5), question_number_label character varying(20), left_item_text character varying(4000), right_item_text character varying(2000), section_id integer, decision_condition_id integer, response_set_id integer, regexp character varying(1000), regexp_error_msg character varying(255), ordinal integer, required boolean, default_value character varying(4000), response_layout character varying(255), width_decimal character varying(10), show_item boolean)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'item_form_metadata', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_item_group (item_group_id integer, name character varying(255), crf_id integer, status_id integer, date_created date, date_updated date, owner_id integer, update_id integer, oc_oid character varying(40))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'item_group', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_item_group_metadata (item_group_metadata_id integer, item_group_id integer, header character varying(255), subheader character varying(255), layout character varying(100), repeat_number integer, repeat_max integer, repeat_array character varying(255), row_start_number integer, crf_version_id integer, item_id integer, ordinal integer, borders integer, show_group boolean, repeating_group boolean)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'item_group_metadata', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_item_reference_type (item_reference_type_id integer, name character varying(255), description character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'item_reference_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_measurement_unit (id integer, oc_oid character varying(40), name character varying(100), description character varying(255), version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'measurement_unit', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_null_value_type (null_value_type_id integer, code character varying(20), name character varying(255), definition character varying(1000), reference character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'null_value_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_blob_triggers (trigger_name character varying(200), trigger_group character varying(200), blob_data bytea)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_blob_triggers', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_calendars (calendar_name character varying(200), calendar bytea)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_calendars', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_cron_triggers (trigger_name character varying(200), trigger_group character varying(200), cron_expression character varying(120), time_zone_id character varying(80))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_cron_triggers', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_fired_triggers (entry_id character varying(95), trigger_name character varying(200), trigger_group character varying(200), is_volatile boolean, instance_name character varying(200), fired_time bigint, priority integer, state character varying(16), job_name character varying(200), job_group character varying(200), is_stateful boolean, requests_recovery boolean)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_fired_triggers', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_job_details (job_name character varying(200), job_group character varying(200), description character varying(250), job_class_name character varying(250), is_durable boolean, is_volatile boolean, is_stateful boolean, requests_recovery boolean, job_data bytea)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_job_details', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_job_listeners (job_name character varying(200), job_group character varying(200), job_listener character varying(200))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_job_listeners', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_locks (lock_name character varying(40))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_locks', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_paused_trigger_grps (trigger_group character varying(200))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_paused_trigger_grps', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_scheduler_state (instance_name character varying(200), last_checkin_time bigint, checkin_interval bigint)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_scheduler_state', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_simple_triggers (trigger_name character varying(200), trigger_group character varying(200), repeat_count bigint, repeat_interval bigint, times_triggered bigint)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_simple_triggers', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_trigger_listeners (trigger_name character varying(200), trigger_group character varying(200), trigger_listener character varying(200))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_trigger_listeners', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_oc_qrtz_triggers (trigger_name character varying(200), trigger_group character varying(200), job_name character varying(200), job_group character varying(200), is_volatile boolean, description character varying(250), next_fire_time bigint, prev_fire_time bigint, priority integer, trigger_state character varying(16), trigger_type character varying(8), start_time bigint, end_time bigint, calendar_name character varying(200), misfire_instr smallint, job_data bytea)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'oc_qrtz_triggers', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_openclinica_version (id integer, name character varying(255), build_number character varying(1000), version integer, update_timestamp timestamp with time zone)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'openclinica_version', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_privilege (priv_id integer, priv_name character varying(50), priv_desc character varying(2000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'privilege', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_resolution_status (resolution_status_id integer, name character varying(50), description character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'resolution_status', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_response_set (response_set_id integer, response_type_id integer, label character varying(80), options_text character varying(4000), options_values character varying(4000), version_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'response_set', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_response_type (response_type_id integer, name character varying(255), description character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'response_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_role_privilege_map (role_id integer, priv_id integer, priv_value character varying(50))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'role_privilege_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule (id integer, name character varying(255), description character varying(255), oc_oid character varying(40), enabled boolean, rule_expression_id integer, owner_id integer, date_created date, date_updated date, update_id integer, status_id integer, version integer, study_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_action (id integer, rule_set_rule_id integer, action_type integer, expression_evaluates_to boolean, message character varying(255), email_to character varying(255), owner_id integer, date_created date, date_updated date, update_id integer, status_id integer, version integer, rule_action_run_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_action', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_action_property (id integer, rule_action_id integer, oc_oid character varying(512), value character varying(512), version integer, rule_expression_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_action_property', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_action_run (id integer, administrative_data_entry boolean, initial_data_entry boolean, double_data_entry boolean, import_data_entry boolean, batch boolean, version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_action_run', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_action_run_log (id integer, action_type integer, item_data_id integer, value character varying(4000), rule_oc_oid character varying(40), version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_action_run_log', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_expression (id integer, value character varying(1025), context integer, owner_id integer, date_created date, date_updated date, update_id integer, status_id integer, version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_expression', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_set (id integer, rule_expression_id integer, study_event_definition_id integer, crf_id integer, crf_version_id integer, study_id integer, owner_id integer, date_created date, date_updated date, update_id integer, status_id integer, version integer, item_id integer, item_group_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_set', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_set_audit (id integer, rule_set_id integer, date_updated date, updater_id integer, status_id integer, version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_set_audit', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_set_rule (id integer, rule_set_id integer, rule_id integer, owner_id integer, date_created date, date_updated date, update_id integer, status_id integer, version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_set_rule', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_rule_set_rule_audit (id integer, rule_set_rule_id integer, date_updated date, updater_id integer, status_id integer, version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'rule_set_rule_audit', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_scd_item_metadata (id integer, scd_item_form_metadata_id integer, control_item_form_metadata_id integer, control_item_name character varying(255), option_value character varying(500), message character varying(3000), version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'scd_item_metadata', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_section (section_id integer, crf_version_id integer, status_id integer, label character varying(2000), title character varying(2000), subtitle character varying(2000), instructions character varying(2000), page_number_label character varying(5), ordinal integer, parent_id integer, date_created date, date_updated date, owner_id integer, update_id integer, borders integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'section', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_status (status_id integer, name character varying(255), description character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'status', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study (study_id integer, parent_study_id integer, unique_identifier character varying(30), secondary_identifier character varying(255), name character varying(255), summary character varying(255), date_planned_start date, date_planned_end date, date_created date, date_updated date, owner_id integer, update_id integer, type_id integer, status_id integer, principal_investigator character varying(255), facility_name character varying(255), facility_city character varying(255), facility_state character varying(20), facility_zip character varying(64), facility_country character varying(64), facility_recruitment_status character varying(60), facility_contact_name character varying(255), facility_contact_degree character varying(255), facility_contact_phone character varying(255), facility_contact_email character varying(255), protocol_type character varying(30), protocol_description character varying(1000), protocol_date_verification date, phase character varying(30), expected_total_enrollment integer, sponsor character varying(255), collaborators character varying(1000), medline_identifier character varying(255), url character varying(255), url_description character varying(255), conditions character varying(500), keywords character varying(255), eligibility character varying(500), gender character varying(30), age_max character varying(3), age_min character varying(3), healthy_volunteer_accepted boolean, purpose character varying(64), allocation character varying(64), masking character varying(30), control character varying(30), assignment character varying(30), endpoint character varying(64), interventions character varying(1000), duration character varying(30), selection character varying(30), timing character varying(30), official_title character varying(255), results_reference boolean, oc_oid character varying(40), old_status_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_event (study_event_id integer, study_event_definition_id integer, study_subject_id integer, location character varying(2000), sample_ordinal integer, date_start timestamp with time zone, date_end timestamp with time zone, owner_id integer, status_id integer, date_created date, date_updated date, update_id integer, subject_event_status_id integer, start_time_flag boolean, end_time_flag boolean)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_event_definition (study_event_definition_id integer, study_id integer, name character varying(2000), description character varying(2000), repeating boolean, type character varying(20), category character varying(2000), owner_id integer, status_id integer, date_created date, date_updated date, update_id integer, ordinal integer, oc_oid character varying(40))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_event_definition', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_group (study_group_id integer, name character varying(255), description character varying(1000), study_group_class_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_group', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_group_class (study_group_class_id integer, name character varying(30), study_id integer, owner_id integer, date_created date, group_class_type_id integer, status_id integer, date_updated date, update_id integer, subject_assignment character varying(30))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_group_class', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_module_status (id integer, study_id integer, study integer, crf integer, event_definition integer, subject_group integer, rule integer, site integer, users integer, version integer, date_created date, date_updated date, owner_id integer, update_id integer, status_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_module_status', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_parameter (study_parameter_id integer, handle character varying(50), name character varying(50), description character varying(255), default_value character varying(50), inheritable boolean, overridable boolean)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_parameter', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_parameter_value (study_parameter_value_id integer, study_id integer, value character varying(50), parameter character varying(50))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_parameter_value', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_subject (study_subject_id integer, label character varying(30), secondary_label character varying(30), subject_id integer, study_id integer, status_id integer, enrollment_date date, date_created date, date_updated date, owner_id integer, update_id integer, oc_oid character varying(40))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_subject', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_type (study_type_id integer, name character varying(255), description character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_study_user_role (role_name character varying(40), study_id integer, status_id integer, owner_id integer, date_created date, date_updated date, update_id integer, user_name character varying(40))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'study_user_role', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_subject (subject_id integer, father_id integer, mother_id integer, status_id integer, date_of_birth date, gender character(1), unique_identifier character varying(255), date_created date, owner_id integer, date_updated date, update_id integer, dob_collected boolean)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'subject', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_subject_event_status (subject_event_status_id integer, name character varying(255), description character varying(1000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'subject_event_status', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_subject_group_map (subject_group_map_id integer, study_group_class_id integer, study_subject_id integer, study_group_id integer, status_id integer, owner_id integer, date_created date, date_updated date, update_id integer, notes character varying(255))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'subject_group_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_usage_statistics_data (id integer, param_key character varying(255), param_value character varying(1000), update_timestamp timestamp with time zone, version integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'usage_statistics_data', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_user_account (user_id integer, user_name character varying(64), passwd character varying(255), first_name character varying(50), last_name character varying(50), email character varying(120), active_study integer, institutional_affiliation character varying(255), status_id integer, owner_id integer, date_created date, date_updated date, date_lastvisit timestamp with time zone, passwd_timestamp date, passwd_challenge_question character varying(64), passwd_challenge_answer character varying(255), phone character varying(64), user_type_id integer, update_id integer, enabled boolean, account_non_locked boolean, lock_counter integer, run_webservices boolean)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'user_account', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_user_role (role_id integer, role_name character varying(50), parent_id integer, role_desc character varying(2000))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'user_role', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_user_type (user_type_id integer, user_type character varying(50))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'user_type', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_versioning_map (crf_version_id integer, item_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'versioning_map', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_discrepancy_note (study_id integer, parent_study_id integer, study_hide_crf boolean, site_hide_crf boolean, discrepancy_note_id integer, entity_id integer, column_name character varying(255), study_subject_id integer, label character varying(30), ss_status_id integer, discrepancy_note_type_id integer, resolution_status_id integer, site_id character varying(30), date_created date, date_updated date, days integer, age integer, event_name character varying, date_start timestamp with time zone, crf_name character varying, status_id integer, item_id integer, entity_name character varying(255), value character varying, entity_type character varying(30), description character varying(255), detailed_notes character varying(1000), total_notes bigint, first_name character varying(50), last_name character varying(50), user_name character varying(64), owner_first_name character varying(50), owner_last_name character varying(50), owner_user_name character varying(64))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_discrepancy_note', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_dn_event_crf (study_id integer, parent_study_id integer, study_hide_crf boolean, site_hide_crf boolean, discrepancy_note_id integer, entity_id integer, column_name character varying(255), study_subject_id integer, label character varying(30), ss_status_id integer, discrepancy_note_type_id integer, resolution_status_id integer, site_id character varying(30), date_created date, date_updated date, days integer, age integer, event_name character varying(2000), date_start timestamp with time zone, crf_name character varying(255), status_id integer, item_id integer, entity_name character varying(255), value text, entity_type character varying(30), description character varying(255), detailed_notes character varying(1000), total_notes bigint, first_name character varying(50), last_name character varying(50), user_name character varying(64), owner_first_name character varying(50), owner_last_name character varying(50), owner_user_name character varying(64))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_dn_event_crf', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_dn_item_data (study_id integer, parent_study_id integer, study_hide_crf boolean, site_hide_crf boolean, discrepancy_note_id integer, entity_id integer, column_name character varying(255), study_subject_id integer, label character varying(30), ss_status_id integer, discrepancy_note_type_id integer, resolution_status_id integer, site_id character varying(30), date_created date, date_updated date, days integer, age integer, event_name character varying(2000), date_start timestamp with time zone, crf_name character varying(255), status_id integer, item_id integer, entity_name character varying(255), value character varying(4000), entity_type character varying(30), description character varying(255), detailed_notes character varying(1000), total_notes bigint, first_name character varying(50), last_name character varying(50), user_name character varying(64), owner_first_name character varying(50), owner_last_name character varying(50), owner_user_name character varying(64))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_dn_item_data', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_dn_stats (discrepancy_note_id integer, days integer, age integer, total_notes bigint, date_created date, date_updated date)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_dn_stats', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_dn_study_event (study_id integer, parent_study_id integer, study_hide_crf boolean, site_hide_crf boolean, discrepancy_note_id integer, entity_id integer, column_name character varying(255), study_subject_id integer, label character varying(30), ss_status_id integer, discrepancy_note_type_id integer, resolution_status_id integer, site_id character varying(30), date_created date, date_updated date, days integer, age integer, event_name character varying(2000), date_start timestamp with time zone, crf_name text, status_id integer, item_id integer, entity_name character varying(255), value text, entity_type character varying(30), description character varying(255), detailed_notes character varying(1000), total_notes bigint, first_name character varying(50), last_name character varying(50), user_name character varying(64), owner_first_name character varying(50), owner_last_name character varying(50), owner_user_name character varying(64))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_dn_study_event', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_dn_study_subject (study_id integer, parent_study_id integer, study_hide_crf boolean, site_hide_crf boolean, discrepancy_note_id integer, entity_id integer, column_name character varying(255), study_subject_id integer, label character varying(30), ss_status_id integer, discrepancy_note_type_id integer, resolution_status_id integer, site_id character varying(30), date_created date, date_updated date, days integer, age integer, event_name text, date_start date, crf_name text, status_id integer, item_id integer, entity_name character varying(255), value text, entity_type character varying(30), description character varying(255), detailed_notes character varying(1000), total_notes bigint, first_name character varying(50), last_name character varying(50), user_name character varying(64), owner_first_name character varying(50), owner_last_name character varying(50), owner_user_name character varying(64))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_dn_study_subject', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_dn_subject (study_id integer, parent_study_id integer, study_hide_crf boolean, site_hide_crf boolean, discrepancy_note_id integer, entity_id integer, column_name character varying(255), study_subject_id integer, label character varying(30), ss_status_id integer, discrepancy_note_type_id integer, resolution_status_id integer, site_id character varying(30), date_created date, date_updated date, days integer, age integer, event_name text, date_start date, crf_name text, status_id integer, item_id integer, entity_name character varying(255), value text, entity_type character varying(30), description character varying(255), detailed_notes character varying(1000), total_notes bigint, first_name character varying(50), last_name character varying(50), user_name character varying(64), owner_first_name character varying(50), owner_last_name character varying(50), owner_user_name character varying(64))  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_dn_subject', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_site_hidden_event_definition_crf (event_definition_crf_id integer, hide_crf boolean, study_id integer, study_event_id integer, crf_version_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_site_hidden_event_definition_crf', updatable 'false'); 
CREATE FOREIGN TABLE public.ft_view_study_hidden_event_definition_crf (event_definition_crf_id integer, hide_crf boolean, study_id integer, study_event_id integer, crf_version_id integer)  
   SERVER :FDWSERVERNAME  OPTIONS (schema_name 'public', table_name 'view_study_hidden_event_definition_crf', updatable 'false'); 
